// Code generated by protoc-gen-uwentity. DO NOT EDIT.
// source: testdata/simple_message.proto
package testdata

// GetEntityIdentifier returns the value from the field marked as the identifier
func (m *SimpleMessage) GetEntityIdentifier() string {
	return m.GetId()
}
