name: Protobuf
on:
  push:
env:
  BUF_VERSION: "1.12.0"
  GO_VERSION: "^1.17"
jobs:
  proto_breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rebase against main
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git rebase origin/main
          git branch -f main origin/main
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ env.BUF_VERSION }}
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1
        env:
          BUF_INPUT_HTTPS_USERNAME: ${{ github.actor }}
          BUF_INPUT_HTTPS_PASSWORD: ${{ github.token }}
        with:
          against: ".git#branch=main"
          buf_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
  proto_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ env.BUF_VERSION }}
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
  proto_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ env.BUF_VERSION }}
          github_token: ${{ github.token }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ env.GO_VERSION }}-proto_generate-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ env.GO_VERSION }}-proto_generate-
      - name: Generate protofiles
        run: buf generate
      - name: Check for changes
        run: git add ./gen && git diff --staged --exit-code
