name: Protobuf
on:
  push:
    branches:
      - main
jobs:
  bsr_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: "0.44.0"
      - uses: bufbuild/buf-push-action@v0.2.0
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
