name: Protobuf
on:
  push:
    branches:
      - main
jobs:
  bsr_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Setup Buf cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/buf
          key: ${{ runner.os }}-buf-${{ inputs.version }}-${{ hashFiles('proto/buf.lock') }}
          restore-keys: |
            ${{ runner.os }}-buf-
      - name: Install Buf
        run: go install github.com/bufbuild/buf/cmd/buf
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: proto
