name: Protobuf
on:
  push:
jobs:
  proto_breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Rebase against main
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git rebase origin/main
          git branch -f main origin/main
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: "0.43.2"
      - uses: bufbuild/buf-breaking-action@v0.2.0
        env:
          BUF_INPUT_HTTPS_USERNAME: ${{ github.actor }}
          BUF_INPUT_HTTPS_PASSWORD: ${{ github.token }}
        with:
          against: ".git#branch=main"
          buf_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
  proto_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: "0.43.2"
      - uses: bufbuild/buf-lint-action@v0.2.0
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
  proto_generate:
    runs-on: ubuntu-latest
    container: "golang:1.16"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: "0.43.2"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-1.16-proto_generate-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-1.16-proto_generate-
      - name: Generate protofiles
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0
          buf generate
      - name: Check for changes
        run: git add ./gen && git diff --staged --exit-code
