name: Protobuf
on:
  push:
    branches:
      - main
env:
  BUF_VERSION: "1.12.0"
jobs:
  bsr_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: ${{ env.BUF_VERSION }}
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: proto
